services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./logs/db:/var/log/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: music_bot/Dockerfile
    volumes:
      - .:/tg-bot
      - ./logs/bot:/var/log/bot
    environment:
      - REDIS_URL=${REDIS_URL}
      - PYTHONPATH=/tg-bot
      - DATABASE_URL=${ASYNC_DATABASE_URL}
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin:
    container_name: admin
    env_file:
      - .env
    build:
      context: .
      dockerfile: admin/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - admin_data:/var/lib/admin/data
      - ./logs/admin:/var/log/admin
    environment:
      - DATABASE_URL=${SYNC_DATABASE_URL}
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
  admin_data:
  redis_data:
  redisinsight_data: